DROP DATABASE IF EXISTS `mychatacct`;
DROP DATABASE IF EXISTS `mychat0_n`;
DROP DATABASE IF EXISTS `mychat1_n`;

CREATE DATABASE `mychatacct` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE `mychat0_n` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE `mychat1_n` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

