DROP DATABASE IF EXISTS `zebra0_n`;
DROP DATABASE IF EXISTS `zebra1_n`;
DROP DATABASE IF EXISTS `zebra2_n`;
DROP DATABASE IF EXISTS `zebra3_n`;
DROP DATABASE IF EXISTS `zebra4_n`;
DROP DATABASE IF EXISTS `zebra5_n`;
DROP DATABASE IF EXISTS `zebra6_n`;
DROP DATABASE IF EXISTS `zebra7_n`;

CREATE DATABASE `zebra0_n` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE `zebra1_n` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE `zebra2_n` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE `zebra3_n` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE `zebra4_n` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE `zebra5_n` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE `zebra6_n` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE `zebra7_n` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
